import type { Token } from "@/types/token";

const now = Date.now();

export const mockTokens: Token[] = [
  {
    id: "sol-1",
    symbol: "BONK",
    name: "Bonk",
    image: "https://cryptologos.cc/logos/bonk1-bonk-logo.png?v=040",
    category: "new_pairs",
    price: 0.00001234,
    change24h: 12.45,
    marketCap: 24000000,
    fdv: 0.08,
    txCount: 124,
    pumpLabel: "6x Pump",
    stats: { buy: 5, sell: 1, holders: 3, bots: 0, whales: 0 },
    updatedAt: now,
  },
  {
    id: "sol-2",
    symbol: "JUP",
    name: "Jupiter",
    image: "https://cryptologos.cc/logos/jupiter-ag-jup-logo.png?v=040",
    category: "final_stretch",
    price: 0.87,
    change24h: -4.12,
    marketCap: 540000000,
    fdv: 0.42,
    txCount: 812,
    pumpLabel: "Stable",
    stats: { buy: 2, sell: 3, holders: 4, bots: 1, whales: 1 },
    updatedAt: now,
  },
  {
    id: "sol-3",
    symbol: "WIF",
    name: "dogwifhat",
    image: "https://cryptologos.cc/logos/dogwifhat-wif-logo.png?v=040",
    category: "new_pairs",
    price: 0.001234,
    change24h: 8.76,
    marketCap: 120000000,
    fdv: 0.15,
    txCount: 456,
    pumpLabel: "4x Pump",
    stats: { buy: 7, sell: 2, holders: 5, bots: 1, whales: 0 },
    updatedAt: now,
  },
  {
    id: "sol-4",
    symbol: "POPCAT",
    name: "Popcat",
    image: "https://cryptologos.cc/logos/popcat-sol-popcat-logo.png?v=040",
    category: "new_pairs",
    price: 0.000567,
    change24h: 15.23,
    marketCap: 45000000,
    fdv: 0.12,
    txCount: 289,
    pumpLabel: "8x Pump",
    stats: { buy: 4, sell: 0, holders: 2, bots: 0, whales: 1 },
    updatedAt: now,
  },
  {
    id: "sol-5",
    symbol: "MEW",
    name: "cat in a dogs world",
    image: "https://cryptologos.cc/logos/catcoin-token-cats-logo.png?v=040",
    category: "new_pairs",
    price: 0.002345,
    change24h: -2.34,
    marketCap: 67000000,
    fdv: 0.09,
    txCount: 167,
    pumpLabel: "2x Pump",
    stats: { buy: 3, sell: 4, holders: 6, bots: 2, whales: 0 },
    updatedAt: now,
  },
  {
    id: "sol-6",
    symbol: "RAY",
    name: "Raydium",
    image: "https://cryptologos.cc/logos/raydium-ray-logo.svg?v=040",
    category: "final_stretch",
    price: 1.23,
    change24h: 3.45,
    marketCap: 320000000,
    fdv: 0.56,
    txCount: 945,
    pumpLabel: "Steady",
    stats: { buy: 6, sell: 2, holders: 8, bots: 1, whales: 2 },
    updatedAt: now,
  },
  {
    id: "sol-7",
    symbol: "ORCA",
    name: "Orca",
    image: "https://cryptologos.cc/logos/orca-orca-logo.svg?v=040",
    category: "final_stretch",
    price: 2.10,
    change24h: -1.89,
    marketCap: 180000000,
    fdv: 0.34,
    txCount: 623,
    pumpLabel: "Holding",
    stats: { buy: 1, sell: 3, holders: 7, bots: 0, whales: 1 },
    updatedAt: now,
  },
  {
    id: "sol-8",
    symbol: "JTO",
    name: "Jito",
    image: "https://cryptologos.cc/logos/enjin-coin-enj-logo.svg?v=040",
    category: "final_stretch",
    price: 3.45,
    change24h: 7.12,
    marketCap: 410000000,
    fdv: 0.67,
    txCount: 734,
    pumpLabel: "5x Pump",
    stats: { buy: 5, sell: 1, holders: 4, bots: 2, whales: 3 },
    updatedAt: now,
  },
  {
    id: "sol-9",
    symbol: "PYTH",
    name: "Pyth Network",
    image: "https://cryptologos.cc/logos/pyth-network-pyth-logo.svg?v=040",
    category: "final_stretch",
    price: 0.34,
    change24h: 9.67,
    marketCap: 89000000,
    fdv: 0.23,
    txCount: 512,
    pumpLabel: "Rising",
    stats: { buy: 8, sell: 2, holders: 5, bots: 1, whales: 0 },
    updatedAt: now,
  },
  {
    id: "sol-10",
    symbol: "HNT",
    name: "Helium",
    image: "https://cryptologos.cc/logos/helium-hnt-logo.svg?v=040",
    category: "migrated",
    price: 5.67,
    change24h: -6.78,
    marketCap: 750000000,
    fdv: 1.20,
    txCount: 1345,
    pumpLabel: "Migrated",
    stats: { buy: 2, sell: 5, holders: 9, bots: 3, whales: 2 },
    updatedAt: now,
  },
  {
    id: "sol-11",
    symbol: "IO",
    name: "io.net",
    image: "https://cryptologos.cc/logos/iotex-iotx-logo.svg?v=040",
    category: "migrated",
    price: 4.12,
    change24h: 11.34,
    marketCap: 290000000,
    fdv: 0.78,
    txCount: 678,
    pumpLabel: "10x Potential",
    stats: { buy: 7, sell: 1, holders: 6, bots: 0, whales: 1 },
    updatedAt: now,
  },
  {
    id: "sol-12",
    symbol: "WEN",
    name: "Wen",
    image: "https://cryptologos.cc/logos/wen-wen-logo.svg?v=040",
    category: "migrated",
    price: 0.0000987,
    change24h: 4.56,
    marketCap: 56000000,
    fdv: 0.11,
    txCount: 345,
    pumpLabel: "Wen Moon",
    stats: { buy: 4, sell: 2, holders: 3, bots: 1, whales: 0 },
    updatedAt: now,
  },
  {
    id: "sol-13",
    symbol: "BODEN",
    name: "Jeo Boden",
    image: "https://cryptologos.cc/logos/book-of-meme-bome-logo.svg?v=040",
    category: "new_pairs",
    price: 0.000456,
    change24h: 38.21,
    marketCap: 18000000,
    fdv: 0.05,
    txCount: 892,
    pumpLabel: "15x Pump",
    stats: { buy: 9, sell: 2, holders: 7, bots: 1, whales: 1 },
    updatedAt: now,
  },
  {
    id: "sol-14",
    symbol: "MOTHER",
    name: "Mother Iggy",
    image: "https://cryptologos.cc/logos/artificial-superintelligence-alliance-fet-logo.svg?v=040",
    category: "new_pairs",
    price: 0.00123,
    change24h: -9.45,
    marketCap: 32000000,
    fdv: 0.18,
    txCount: 567,
    pumpLabel: "Dip Buy",
    stats: { buy: 3, sell: 6, holders: 4, bots: 2, whales: 0 },
    updatedAt: now,
  },
  {
    id: "sol-15",
    symbol: "GIGA",
    name: "Gigachad",
    image: "https://cryptologos.cc/logos/waykichain-wicc-logo.svg?v=040",
    category: "new_pairs",
    price: 0.0000789,
    change24h: 72.34,
    marketCap: 8900000,
    fdv: 0.03,
    txCount: 1203,
    pumpLabel: "30x Pump",
    stats: { buy: 12, sell: 1, holders: 8, bots: 0, whales: 2 },
    updatedAt: now,
  },
  {
    id: "sol-16",
    symbol: "TNSR",
    name: "Tensor",
    image: "https://cryptologos.cc/logos/bittensor-tao-logo.svg?v=040",
    category: "final_stretch",
    price: 0.78,
    change24h: 5.67,
    marketCap: 156000000,
    fdv: 0.45,
    txCount: 789,
    pumpLabel: "Strong",
    stats: { buy: 5, sell: 2, holders: 6, bots: 1, whales: 1 },
    updatedAt: now,
  },
  {
    id: "sol-17",
    symbol: "KMNO",
    name: "Kamino Finance",
    image: "https://cryptologos.cc/logos/nakamoto-games-naka-logo.svg?v=040",
    category: "final_stretch",
    price: 0.056,
    change24h: -3.21,
    marketCap: 48000000,
    fdv: 0.29,
    txCount: 412,
    pumpLabel: "Accumulate",
    stats: { buy: 4, sell: 3, holders: 5, bots: 0, whales: 1 },
    updatedAt: now,
  },
  {
    id: "sol-18",
    symbol: "DRIFT",
    name: "Drift",
    image: "https://cryptologos.cc/logos/dragonchain-drgn-logo.svg?v=040",
    category: "final_stretch",
    price: 0.41,
    change24h: 14.89,
    marketCap: 82000000,
    fdv: 0.61,
    txCount: 934,
    pumpLabel: "Breakout",
    stats: { buy: 8, sell: 1, holders: 7, bots: 1, whales: 2 },
    updatedAt: now,
  },
  {
    id: "sol-19",
    symbol: "SLERF",
    name: "Slerf",
    image: "https://cryptologos.cc/logos/smooth-love-potion-slp-logo.svg?v=040",
    category: "migrated",
    price: 0.189,
    change24h: -7.34,
    marketCap: 94000000,
    fdv: 0.88,
    txCount: 623,
    pumpLabel: "Recovery",
    stats: { buy: 2, sell: 5, holders: 6, bots: 2, whales: 1 },
    updatedAt: now,
  },
  {
    id: "sol-20",
    symbol: "BILLY",
    name: "Billy",
    image: "https://cryptologos.cc/logos/bittorrent-bttold-logo.svg?v=040",
    category: "new_pairs",
    price: 0.0000345,
    change24h: 45.67,
    marketCap: 14000000,
    fdv: 0.04,
    txCount: 1056,
    pumpLabel: "20x Pump",
    stats: { buy: 10, sell: 2, holders: 9, bots: 0, whales: 1 },
    updatedAt: now,
  },
  {
    id: "sol-21",
    symbol: "MICHI",
    name: "michi",
    image: "https://cryptologos.cc/logos/mina-mina-logo.svg?v=040",
    category: "new_pairs",
    price: 0.000987,
    change24h: 28.91,
    marketCap: 21000000,
    fdv: 0.07,
    txCount: 789,
    pumpLabel: "12x Pump",
    stats: { buy: 7, sell: 3, holders: 5, bots: 1, whales: 0 },
    updatedAt: now,
  },
  {
    id: "sol-22",
    symbol: "AURA",
    name: "Aura",
    image: "https://cryptologos.cc/logos/aurora-aoa-logo.svg?v=040",
    category: "new_pairs",
    price: 0.0021,
    change24h: -12.45,
    marketCap: 38000000,
    fdv: 0.22,
    txCount: 534,
    pumpLabel: "Correction",
    stats: { buy: 3, sell: 7, holders: 4, bots: 3, whales: 1 },
    updatedAt: now,
  },
];

export async function fetchTokens(): Promise<Token[]> {
  await new Promise((res) => setTimeout(res, 600));
  return mockTokens;
}